mindmap
  root((Factores espaciales en la participación en el Turismo Rural Vivencial – Llachón))

    Cercanía_al_lago
      ("Mayor atractivo paisajístico")
      ("Acceso rápido a actividades lacustres")
      ("Preferencia de turistas por vista y proximidad")

    Accesibilidad_vial
      ("Proximidad a caminos principales")
      ("Mejor conexión con embarcadero y plaza")
      ("Facilita llegada de turistas y agencias")

    Pendiente_del_terreno
      ("Zonas planas favorecen infraestructura turística")
      ("Laderas fuertes incrementan costos de construcción")
      ("Terrenos accesibles mejoran movilidad del visitante")

    Concentración_de_viviendas
      ("Núcleos favorecen organización colectiva")
      ("Mayor visibilidad y señalización para visitantes")
      ("Viviendas aisladas muestran menor participación")

    Proximidad_a_servicios
      ("Cercanía a puntos comunitarios")
      ("Acceso a energía, agua y señal móvil")
      ("Mayor viabilidad para alojar turistas")

    Dinámicas_territoriales
      ("Integración a circuitos turísticos locales")
      ("Relación con rutas y miradores naturales")
      ("Articulación con tejido rural existente")
