flowchart TD

    A[Ubicación geográfica de los establecimientos de salud] --> B(Distancia a la población)
    A --> C(Accesos viales)
    A --> D(Dispersión poblacional)

    B --> E(Barreras de acceso físico)
    C --> E
    D --> E

    E --> F(Menor uso real de los servicios)
    F --> G(Menor efectividad de las políticas de cobertura y equidad)

    G --> H(Necesidad de adaptarse al territorio)

    H --> H1(Fortalecer puestos periféricos)
    H --> H2(Brigadas móviles y telemedicina)
    H --> H3(Mejorar transporte sanitario y vías de acceso)

